# Generated by Django 2.2 on 2019-10-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
