# Generated by Django 2.2 on 2019-10-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0002_cloths_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloths',
            name='add_date',
        ),
    ]
