# Generated by Django 2.2 on 2019-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payments_pay_mthd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transactid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
