# Generated by Django 2.2 on 2019-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cust_email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cust_phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
