# Generated by Django 2.2 on 2019-08-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='empPhone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
