# Generated by Django 2.2 on 2019-08-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190826_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='image',
            field=models.ImageField(default='defaulf.jpg', upload_to='emply_pics'),
        ),
    ]
