# Generated by Django 2.2 on 2019-08-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190826_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='empRole',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
