# Generated by Django 2.2 on 2019-08-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employeeinfo_emprole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='empRole',
            field=models.CharField(max_length=30),
        ),
    ]
