# Generated by Django 2.2 on 2019-08-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190827_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='empAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='empBod',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='empDept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='empDateEmpl',
            new_name='employment_Date',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='empGender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='empMarrigStatus',
            new_name='marrig_Status',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='empPhone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='emp_Role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='empSalary',
            new_name='salary',
        ),
    ]
