# Generated by Django 2.2 on 2019-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190827_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='image',
            field=models.ImageField(default='defaulf.png', upload_to='emply_pics'),
        ),
    ]
