# Generated by Django 2.2 on 2019-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190827_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='address',
            field=models.TextField(max_length=225),
        ),
    ]
