# Generated by Django 2.2 on 2019-08-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190827_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='birth_date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='employment_Date',
            field=models.DateField(max_length=10),
        ),
    ]
