# Generated by Django 2.2 on 2019-08-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190828_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='employment_Date',
        ),
    ]
