# Generated by Django 2.2 on 2019-08-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190828_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='salary',
        ),
    ]
