# Generated by Django 2.2 on 2019-08-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_employeeinfo_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='employment_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
