# Generated by Django 2.2 on 2019-08-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190829_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='address',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='marrig_Status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
