# Generated by Django 2.2 on 2019-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190829_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='address',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='department',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='employment_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='marrig_Status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
