# Generated by Django 2.2 on 2019-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190829_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='image',
            field=models.ImageField(default='default.png', upload_to='emply_pics'),
        ),
    ]
