# Generated by Django 2.2 on 2019-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190829_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
