# Generated by Django 2.2 on 2019-09-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='mac_addr',
        ),
    ]
