# Generated by Django 2.2 on 2019-10-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_logs_mac_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
