# Generated by Django 2.2 on 2019-10-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191021_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='image',
            field=models.ImageField(upload_to='emply_pics'),
        ),
    ]
