# Generated by Django 2.2 on 2019-08-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_auto_20190826_0804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
