# Generated by Django 2.2 on 2019-09-02 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=15)),
                ('total_item', models.IntegerField()),
                ('total', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customers')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('sub_total', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('orderid', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Orders')),
            ],
        ),
    ]
