# Generated by Django 2.2 on 2019-09-02 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='orderid',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='uniqueid',
            field=models.CharField(default='uniqueidrandoms', max_length=100),
        ),
    ]
