# Generated by Django 2.2 on 2019-09-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190902_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='uniqueid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='uniqueid',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='transid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='transid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
