# Generated by Django 2.2 on 2019-09-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='transid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
