# Generated by Django 2.2 on 2019-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190909_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
