# Generated by Django 2.2 on 2019-09-13 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_name', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=70)),
                ('manufactural', models.CharField(blank=True, max_length=70)),
                ('date_bought', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='wmachines')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
