# Generated by Django 2.2 on 2019-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
